FROM {{builder}} AS builder
{{#if ignore_tests}}
RUN {{ cmd_one }}
{{else}}
RUN {{ cmd_one }} \
  && {{ cmd_two }} \
  && {{ cmd_three }} \
  && {{ cmd_four }} \
  && {{ cmd_five }}

RUN {{ test_one }}
{{/if}}

COPY Cargo.toml .
COPY ./src ./src

RUN cargo build --release

FROM {{formation}}
COPY --from=builder /target/release/hello_world /var/task/
CMD ["./hello_world"]
