FROM {{builder}} AS builder
{{#if ignore_tests}}
RUN {{ cmd_one }}
{{else}}
RUN {{ cmd_one }} \
  && {{ cmd_two }} \
  && {{ cmd_three }} \
  && {{ cmd_four }} \
  && {{ cmd_five }}

RUN {{ test_one }}
{{/if}}
FROM {{formation}}
