[package]
name = "mesa"
version = "0.1.0"
authors = ["Davis Van Sant <davisvansant@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.clap]
version = "2.33.3"
default-features = false

[dependencies.mesa_strata]
version = "0.1.0"
path = "../mesa_strata"

[dependencies.serde]
version = "1.0.119"
default-features = false
features = [ "derive" ]

[dependencies.tokio]
version = "0.2.23"
default-features = false
features = [ "full" ]

[dependencies.toml]
version = "0.5.8"
