[package]
name = "mesa"
version = "0.1.0"
authors = ["Davis Van Sant <davisvansant@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.bollard]
version = "0.9.0"

[dependencies.clap]
version = "2.33.3"
default-features = false

[dependencies.futures]
version = "0.3.9"

[dependencies.handlebars]
version = "3.5.2"
default-features = false

[dependencies.semver]
version = "0.11.0"
default-features = false
features = []

[dependencies.serde]
version = "1.0.119"
default-features = false
features = [ "derive" ]

[dependencies.serde_json]
version = "1.0.61"
default-features = false
features = [ "std" ]

[dependencies.tar]
version = "0.4.30"

[dependencies.tokio]
version = "0.2.23"
default-features = false
features = [ "full" ]

[dependencies.toml]
version = "0.5.8"
